// @generated by scripts/generate-renderer-contracts.mjs from contracts/renderer-protocol.json.
// Do not edit by hand.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum RendererEvent {
    RendererStarted {
        mode: String,
        output: String,
    },
    PipelinePlanResolved {
        route: String,
        effective_concurrency: u32,
        probe_tier: String,
        segment_count: usize,
        capture_mode: String,
        conversion_mode: String,
        encoder_mode: String,
        planned_encoder_backend: String,
        encoder_backend: String,
    },
    FrameRendered {
        frame: u32,
        capture_backend: Option<String>,
        surface_format_in: Option<String>,
    },
    FrameEncoded {
        frame: u32,
        frames_encoded: u32,
    },
    RendererFinished {
        frames_rendered: u32,
        frames_encoded: u32,
        fallback_used: bool,
        fallback_reason: Option<String>,
        cpu_readback_frames: u64,
        capture_backend: Option<String>,
        conversion_backend: Option<String>,
        encoder_backend: Option<String>,
    },
    RendererFailed {
        error: String,
    },
}

pub const BROWSER_PROTOCOL_VERSION: u32 = 4;
pub const OUTPUT_API_VERSION: u32 = 1;
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RenderOperation {
    #[default]
    Render,
    Inspect,
    Frame,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RenderMode {
    Composition,
    Url,
    CompositionWorker,
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RendererAcceleration {
    Required,
    #[default]
    Auto,
    Off,
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RendererAssemblyMode {
    #[default]
    Auto,
    Reference,
    Segments,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RenderCaptureProbe {
    AcceleratedPaint,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RendererConcurrency {
    Auto,
    Workers(std::num::NonZeroU32),
}
impl Serialize for RendererConcurrency {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Auto => serializer.serialize_str("auto"),
            Self::Workers(workers) => serializer.serialize_u32(workers.get()),
        }
    }
}
impl<'de> Deserialize<'de> for RendererConcurrency {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct UnionVisitor;
        impl<'de> serde::de::Visitor<'de> for UnionVisitor {
            type Value = RendererConcurrency;
            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("renderer concurrency must be a positive integer or auto")
            }
            fn visit_str<E: serde::de::Error>(self, value: &str) -> Result<Self::Value, E> {
                if value == "auto" {
                    Ok(RendererConcurrency::Auto)
                } else {
                    Err(E::custom(
                        "renderer concurrency must be a positive integer or auto",
                    ))
                }
            }
            fn visit_u64<E: serde::de::Error>(self, value: u64) -> Result<Self::Value, E> {
                u32::try_from(value)
                    .ok()
                    .and_then(std::num::NonZeroU32::new)
                    .map(RendererConcurrency::Workers)
                    .ok_or_else(|| {
                        E::custom("renderer concurrency must be a positive integer or auto")
                    })
            }
            fn visit_i64<E: serde::de::Error>(self, value: i64) -> Result<Self::Value, E> {
                if value <= 0 {
                    Err(E::custom(
                        "renderer concurrency must be a positive integer or auto",
                    ))
                } else {
                    self.visit_u64(value as u64)
                }
            }
        }
        deserializer.deserialize_any(UnionVisitor)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AudioEnvelopePoint {
    pub sample: u64,
    pub gain: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AudioClip {
    pub source: String,
    #[serde(rename = "startSample")]
    pub start_sample: i64,
    #[serde(rename = "sourceStartSample")]
    pub source_start_sample: u64,
    #[serde(rename = "durationSamples")]
    pub duration_samples: u64,
    pub gain: f64,
    #[serde(rename = "volumeEnvelope", skip_serializing_if = "Option::is_none")]
    pub volume_envelope: Option<Vec<AudioEnvelopePoint>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AudioPlan {
    #[serde(rename = "sampleRate")]
    pub sample_rate: u64,
    #[serde(rename = "durationSamples")]
    pub duration_samples: u64,
    pub clips: Vec<AudioClip>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OutputFrameRange {
    #[serde(rename = "startFrame")]
    pub start_frame: u32,
    #[serde(rename = "endFrame")]
    pub end_frame: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CompositionManifest {
    pub id: String,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    #[serde(rename = "durationFrames")]
    pub duration_frames: u32,
    pub target: Option<String>,
    pub url: Option<String>,
    #[serde(
        rename = "maxConcurrency",
        default,
        deserialize_with = "deserialize_max_concurrency"
    )]
    pub max_concurrency: Option<std::num::NonZeroU32>,
}

fn deserialize_max_concurrency<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<std::num::NonZeroU32>, D::Error> {
    <Option<std::num::NonZeroU32>>::deserialize(deserializer)
        .map_err(|_| serde::de::Error::custom("maxConcurrency must be a positive integer"))
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RenderSession {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "sourceVersion", skip_serializing_if = "Option::is_none")]
    pub source_version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RenderContext {
    #[serde(rename = "compositionId")]
    pub composition_id: String,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    #[serde(rename = "durationFrames")]
    pub duration_frames: u32,
    pub target: Option<String>,
    #[serde(rename = "inputProps", skip_serializing_if = "Option::is_none")]
    pub input_props: Option<serde_json::Value>,
    #[serde(rename = "renderSession", skip_serializing_if = "Option::is_none")]
    pub render_session: Option<RenderSession>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct RenderJob {
    #[serde(default = "default_render_job_operation")]
    pub operation: RenderOperation,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_frame: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_range: Option<OutputFrameRange>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_path: Option<String>,
    pub mode: RenderMode,
    pub composition_id: Option<String>,
    pub composition: Option<CompositionManifest>,
    pub serve_url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub render_session: Option<RenderSession>,
    pub selector: Option<String>,
    pub output: String,
    pub codec: String,
    pub container: Option<String>,
    pub audio_codec: Option<String>,
    pub media_backend: Option<String>,
    pub video_profile: Option<String>,
    pub pixel_format: Option<String>,
    pub bitrate_bps: Option<u64>,
    #[serde(default = "default_render_job_acceleration")]
    pub acceleration: RendererAcceleration,
    pub concurrency: Option<RendererConcurrency>,
    #[serde(default = "default_render_job_assembly_mode")]
    pub assembly_mode: RendererAssemblyMode,
    pub capture_probe: Option<RenderCaptureProbe>,
    pub report_path: Option<String>,
    pub worker_report_path: Option<String>,
    pub event_log_path: Option<String>,
    #[serde(default = "default_render_job_verify_segments")]
    pub verify_segments: bool,
    pub input_props_path: Option<String>,
    pub frame_start: Option<u32>,
    pub frame_end: Option<u32>,
    pub frame_step: Option<std::num::NonZeroU32>,
    pub chunk_output: Option<String>,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
struct RawRenderJob {
    #[serde(default = "default_render_job_operation")]
    pub operation: RenderOperation,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_frame: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_range: Option<OutputFrameRange>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_path: Option<String>,
    pub mode: RenderMode,
    pub composition_id: Option<String>,
    pub composition: Option<CompositionManifest>,
    pub serve_url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub render_session: Option<RenderSession>,
    pub selector: Option<String>,
    pub output: String,
    pub codec: String,
    pub container: Option<String>,
    pub audio_codec: Option<String>,
    pub media_backend: Option<String>,
    pub video_profile: Option<String>,
    pub pixel_format: Option<String>,
    pub bitrate_bps: Option<u64>,
    #[serde(default = "default_render_job_acceleration")]
    pub acceleration: RendererAcceleration,
    pub concurrency: Option<RendererConcurrency>,
    #[serde(default = "default_render_job_assembly_mode")]
    pub assembly_mode: RendererAssemblyMode,
    pub capture_probe: Option<RenderCaptureProbe>,
    pub report_path: Option<String>,
    pub worker_report_path: Option<String>,
    pub event_log_path: Option<String>,
    #[serde(default = "default_render_job_verify_segments")]
    pub verify_segments: bool,
    pub input_props_path: Option<String>,
    pub frame_start: Option<u32>,
    pub frame_end: Option<u32>,
    pub frame_step: Option<std::num::NonZeroU32>,
    pub chunk_output: Option<String>,
}

impl<'de> Deserialize<'de> for RenderJob {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = RawRenderJob::deserialize(deserializer)?;
        let job = Self {
            operation: raw.operation,
            output_frame: raw.output_frame,
            output_range: raw.output_range,
            result_path: raw.result_path,
            mode: raw.mode,
            composition_id: raw.composition_id,
            composition: raw.composition,
            serve_url: raw.serve_url,
            render_session: raw.render_session,
            selector: raw.selector,
            output: raw.output,
            codec: raw.codec,
            container: raw.container,
            audio_codec: raw.audio_codec,
            media_backend: raw.media_backend,
            video_profile: raw.video_profile,
            pixel_format: raw.pixel_format,
            bitrate_bps: raw.bitrate_bps,
            acceleration: raw.acceleration,
            concurrency: raw.concurrency,
            assembly_mode: raw.assembly_mode,
            capture_probe: raw.capture_probe,
            report_path: raw.report_path,
            worker_report_path: raw.worker_report_path,
            event_log_path: raw.event_log_path,
            verify_segments: raw.verify_segments,
            input_props_path: raw.input_props_path,
            frame_start: raw.frame_start,
            frame_end: raw.frame_end,
            frame_step: raw.frame_step,
            chunk_output: raw.chunk_output,
        };
        validate_render_job_mode(&job).map_err(serde::de::Error::custom)?;
        Ok(job)
    }
}

fn default_render_job_operation() -> RenderOperation {
    RenderOperation::Render
}

fn default_render_job_acceleration() -> RendererAcceleration {
    RendererAcceleration::Auto
}

fn default_render_job_assembly_mode() -> RendererAssemblyMode {
    RendererAssemblyMode::Auto
}

fn default_render_job_verify_segments() -> bool {
    false
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProgressEvent {
    pub frame: u32,
    pub total_frames: u32,
}

pub(crate) fn validate_render_job_mode(job: &RenderJob) -> Result<(), String> {
    match job.mode {
        RenderMode::Composition => {
            if job.frame_start.is_some()
                || job.frame_end.is_some()
                || job.frame_step.is_some()
                || job.chunk_output.is_some()
            {
                return Err(
                    "composition job cannot include composition_worker frame/chunk fields"
                        .to_owned(),
                );
            }
        }
        RenderMode::Url => {
            if job.frame_start.is_some()
                || job.frame_end.is_some()
                || job.frame_step.is_some()
                || job.chunk_output.is_some()
            {
                return Err(
                    "url job cannot include composition_worker frame/chunk fields".to_owned(),
                );
            }
            if job.selector.is_none() {
                return Err("url job requires selector".to_owned());
            }
        }
        RenderMode::CompositionWorker => {
            if job.frame_start.is_none() {
                return Err("composition_worker job requires frame_start".to_owned());
            }
            if job.frame_end.is_none() {
                return Err("composition_worker job requires frame_end".to_owned());
            }
            if job.chunk_output.is_none() {
                return Err("composition_worker job requires chunk_output".to_owned());
            }
        }
    }
    Ok(())
}
