[package]
name = "velocast-renderer"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "velocast-renderer"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url = "=2.5.8"
ureq = { version = "=3.3.0", default-features = false }
sha2 = "=0.10.9"
velocast-protocol = { path = "../protocol" }
velocast-renderer-policy = { path = "../renderer-policy" }

[target.'cfg(windows)'.dependencies]
ffmpeg-sys-next = { version = "9.0.0", default-features = false, features = ["avcodec", "avformat"] }
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }
windows = { version = "0.62.2", features = ["Win32_Security", "Win32_Foundation", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D_Fxc", "Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_System_Com"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"
